name: 04 - Using Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app

      - name: Run tests
        run: npm test
        working-directory: 04-using-actions/react-app

      - name: Build project
        run: npm run build
        working-directory: 04-using-actions/react-app
