name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: ${{ vars.WORKFLOW_VAR || 'I am a workflow env var' }}
  OVERWRITTEN: ${{ vars.OVERWRITTEN || 'I will be overwritten' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: ${{ vars.JOB_VAR || 'I am a job env var' }}
      OVERWRITTEN: ${{ vars.OVERWRITTEN || 'I have been overwritten at the job level' }}

    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: ${{ vars.STEP_VAR || 'I am a step env var' }}
          step_var2: ${{ vars.step_var2 || 'I am another step var' }}
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten: $OVERWRITTEN"

      - name: Overwrite Job Variable
        env:
          OVERWRITTEN: ${{ vars.OVERWRITTEN || 'I have been overwritten at the step level' }}
        run: echo "Step env var: $OVERWRITTEN"
